basePath: /
host: localhost:8000
info:
  contact:
    email: maxime.marcuccilli@gmail.com
    name: Maxime Marcuccilli
    url: https://www.linkedin.com/in/maxime-marcuccilli/
  description: A custom FizzBuzz API in Go using Gin Framework
  termsOfService: http://swagger.io/terms/
  title: LBC Test API
  version: "1.0"
paths:
  /fizzbuzz:
    get:
      description: 'Take 5 parameters : int1, int2, limit, str1, str2. It plays with
        it then responds with a JSON array of the modified string.'
      parameters:
      - description: first integer
        in: query
        name: int1
        required: true
        type: string
      - description: second integer
        in: query
        name: int2
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      - description: first string
        in: query
        name: str1
        required: true
        type: string
      - description: second string
        in: query
        name: str2
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: FizzBuzz a string and get a JSON array !
      tags:
      - fizzbuzz
  /queries:
    get:
      description: Responds a string of the most hit FizzBuzz Query.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get most popular query as string
      tags:
      - queries
schemes:
- http
swagger: "2.0"
